"""enum in fiction

Revision ID: de214504d2bd
Revises: d45adea36770
Create Date: 2026-05-06 11:41:46.931792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from db.schemas import media_type

# revision identifiers, used by Alembic.
revision: str = 'de214504d2bd'
down_revision: Union[str, Sequence[str], None] = 'd45adea36770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Fiction', 'medium',
                    type_=sa.Enum(media_type, name="mediumenum"),
                    existing_type=sa.String(255),
                    nullable=False
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'Fiction',
        'medium',
        type_=sa.String(255),
        existing_type=sa.Enum(media_type, name="mediumenum"),
        nullable=False
    )
    # ### end Alembic commands ###
